namespace Madden26Plugin.Roster;

public static class SidearmTeamMap
{
    public static Dictionary<string, string> Teams { get; } = new()
    {
        // ACC
        ["Boston College"] = "bceagles.com",
        ["California"] = "calbears.com",
        ["Clemson"] = "clemsontigers.com",
        ["Duke"] = "goduke.com",
        ["Florida State"] = "seminoles.com",
        ["Georgia Tech"] = "ramblinwreck.com",
        ["Louisville"] = "gocards.com",
        ["Miami"] = "miamihurricanes.com",
        ["North Carolina"] = "goheels.com",
        ["NC State"] = "gopack.com",
        ["Pittsburgh"] = "pittsburghpanthers.com",
        ["SMU"] = "smumustangs.com",
        ["Stanford"] = "gostanford.com",
        ["Syracuse"] = "cuse.com",
        ["Virginia"] = "virginiasports.com",
        ["Virginia Tech"] = "hokiesports.com",
        ["Wake Forest"] = "godeacs.com",

        // Big Ten
        ["Illinois"] = "fightingillini.com",
        ["Indiana"] = "iuhoosiers.com",
        ["Iowa"] = "hawkeyesports.com",
        ["Maryland"] = "umterps.com",
        ["Michigan"] = "mgoblue.com",
        ["Michigan State"] = "msuspartans.com",
        ["Minnesota"] = "gophersports.com",
        ["Nebraska"] = "huskers.com",
        ["Northwestern"] = "nusports.com",
        ["Ohio State"] = "ohiostatebuckeyes.com",
        ["Oregon"] = "goducks.com",
        ["Penn State"] = "gopsusports.com",
        ["Purdue"] = "purduesports.com",
        ["Rutgers"] = "scarletknights.com",
        ["UCLA"] = "uclabruins.com",
        ["USC"] = "usctrojans.com",
        ["Washington"] = "gohuskies.com",
        ["Wisconsin"] = "uwbadgers.com",

        // Big 12
        ["Arizona"] = "arizonawildcats.com",
        ["Arizona State"] = "thesundevils.com",
        ["Baylor"] = "baylorbears.com",
        ["BYU"] = "byucougars.com",
        ["Cincinnati"] = "gobearcats.com",
        ["Colorado"] = "cubuffs.com",
        ["Houston"] = "uhcougars.com",
        ["Iowa State"] = "cyclones.com",
        ["Kansas"] = "kuathletics.com",
        ["Kansas State"] = "kstatesports.com",
        ["Oklahoma State"] = "okstate.com",
        ["TCU"] = "gofrogs.com",
        ["Texas Tech"] = "texastech.com",
        ["UCF"] = "ucfknights.com",
        ["Utah"] = "utahutes.com",
        ["West Virginia"] = "wvusports.com",

        // SEC
        ["Alabama"] = "rolltide.com",
        ["Arkansas"] = "arkansasrazorbacks.com",
        ["Auburn"] = "auburntigers.com",
        ["Florida"] = "floridagators.com",
        ["Georgia"] = "georgiadogs.com",
        ["Kentucky"] = "ukathletics.com",
        ["LSU"] = "lsusports.net",
        ["Mississippi State"] = "hailstate.com",
        ["Missouri"] = "mutigers.com",
        ["Oklahoma"] = "soonersports.com",
        ["Ole Miss"] = "olemisssports.com",
        ["South Carolina"] = "gamecocksonline.com",
        ["Tennessee"] = "utsports.com",
        ["Texas"] = "texassports.com",
        ["Texas A&M"] = "12thman.com",
        ["Vanderbilt"] = "vucommodores.com",

        // AAC
        ["Army"] = "goarmywestpoint.com",
        ["Charlotte"] = "charlotte49ers.com",
        ["East Carolina"] = "ecupirates.com",
        ["Florida Atlantic"] = "fausports.com",
        ["Memphis"] = "gotigersgo.com",
        ["Navy"] = "navysports.com",
        ["North Texas"] = "meangreensports.com",
        ["Rice"] = "riceowls.com",
        ["South Florida"] = "gousfbulls.com",
        ["Temple"] = "owlsports.com",
        ["Tulane"] = "tulanegreenwave.com",
        ["Tulsa"] = "tulsahurricane.com",
        ["UAB"] = "uabsports.com",
        ["UTSA"] = "goutsa.com",

        // Conference USA
        ["FIU"] = "fiusports.com",
        ["Jacksonville State"] = "jsugamecocksports.com",
        ["Kennesaw State"] = "kennesawstateathletics.com",
        ["Liberty"] = "libertyflames.com",
        ["Louisiana Tech"] = "latechsports.com",
        ["Middle Tennessee"] = "goblueraiders.com",
        ["New Mexico State"] = "nmstatesports.com",
        ["Sam Houston"] = "gobearkats.com",
        ["UTEP"] = "utepathletics.com",
        ["Western Kentucky"] = "wkusports.com",

        // MAC
        ["Akron"] = "gozips.com",
        ["Ball State"] = "ballstatesports.com",
        ["Bowling Green"] = "bgsufalcons.com",
        ["Buffalo"] = "ubbulls.com",
        ["Central Michigan"] = "cmuchippewas.com",
        ["Eastern Michigan"] = "emueagles.com",
        ["Kent State"] = "kentstatesports.com",
        ["Miami (OH)"] = "miamiredhawks.com",
        ["Northern Illinois"] = "niuhuskies.com",
        ["Ohio"] = "ohiobobcats.com",
        ["Toledo"] = "utrockets.com",
        ["Western Michigan"] = "wmubroncos.com",

        // Mountain West
        ["Air Force"] = "goairforcefalcons.com",
        ["Boise State"] = "broncosports.com",
        ["Colorado State"] = "csurams.com",
        ["Fresno State"] = "gobulldogs.com",
        ["Hawaii"] = "hawaiiathletics.com",
        ["Nevada"] = "nevadawolfpack.com",
        ["New Mexico"] = "golobos.com",
        ["San Diego State"] = "goaztecs.com",
        ["San José State"] = "sjsuspartans.com",
        ["UNLV"] = "unlvrebels.com",
        ["Utah State"] = "utahstateaggies.com",
        ["Wyoming"] = "gowyo.com",

        // Sun Belt
        ["Appalachian State"] = "appstatesports.com",
        ["Arkansas State"] = "astateredwolves.com",
        ["Coastal Carolina"] = "goccusports.com",
        ["Georgia Southern"] = "georgiasoutherneagles.com",
        ["Georgia State"] = "georgiastatesports.com",
        ["James Madison"] = "jmusports.com",
        ["Louisiana"] = "ragincajuns.com",
        ["Louisiana-Monroe"] = "ulmwarhawks.com",
        ["Marshall"] = "herdzone.com",
        ["Old Dominion"] = "odusports.com",
        ["South Alabama"] = "usajaguars.com",
        ["Southern Miss"] = "southernmiss.com",
        ["Texas State"] = "txstbobcats.com",
        ["Troy"] = "troytrojans.com",

        // Independents
        ["Connecticut"] = "uconnhuskies.com",
        ["Notre Dame"] = "fightingirish.com",
        ["UMass"] = "umassathletics.com",

        // FCS Teams in Game
        ["Alabama A&M"] = "aamusports.com",
        ["Alabama State"] = "bamastatesports.com",
        ["Alcorn State"] = "alcornsports.com",
        ["Arkansas-Pine Bluff"] = "uapblionsroar.com",
        ["Austin Peay"] = "letsgopeay.com",
        ["Bethune-Cookman"] = "bcuathletics.com",
        ["Brown"] = "brownbears.com",
        ["Butler"] = "butlersports.com",
        ["Campbell"] = "gocamels.com",
        ["Central Arkansas"] = "ucasports.com",
        ["Central Connecticut"] = "ccsubluedevils.com",
        ["Charleston Southern"] = "csusports.com",
        ["Chattanooga"] = "gomocs.com",
        ["Columbia"] = "gocolumbialions.com",
        ["Cornell"] = "cornellbigred.com",
        ["Dartmouth"] = "dartmouthsports.com",
        ["Davidson"] = "davidsonwildcats.com",
        ["Dayton"] = "daytonflyers.com",
        ["Delaware State"] = "dsuhornets.com",
        ["Drake"] = "godrakebulldogs.com",
        ["Eastern Illinois"] = "eiupanthers.com",
        ["Eastern Kentucky"] = "ekusports.com",
        ["Eastern Washington"] = "goeags.com",
        ["Elon"] = "elonphoenix.com",
        ["Florida A&M"] = "famuathletics.com",
        ["Fordham"] = "fordhamsports.com",
        ["Furman"] = "furmanpaladins.com",
        ["Gardner-Webb"] = "gwusports.com",
        ["Georgetown"] = "guhoyas.com",
        ["Grambling State"] = "gsutigers.com",
        ["Hampton"] = "hamptonpirates.com",
        ["Harvard"] = "gocrimson.com",
        ["Holy Cross"] = "goholycross.com",
        ["Howard"] = "hubison.com",
        ["Idaho"] = "govandals.com",
        ["Idaho State"] = "isubengals.com",
        ["Illinois State"] = "goredbirds.com",
        ["Indiana State"] = "gosycamores.com",
        ["Jackson State"] = "jsutigers.com",
        ["Lafayette"] = "goleopards.com",
        ["Lehigh"] = "lehighsports.com",
        ["Lindenwood"] = "lindenwoodlions.com",
        ["LIU"] = "liuathletics.com",
        ["Maine"] = "goblackbears.com",
        ["Marist"] = "goredfoxes.com",
        ["McNeese"] = "mcneesesports.com",
        ["Mercer"] = "mercerbears.com",
        ["Mississippi Valley State"] = "mvsusports.com",
        ["Missouri State"] = "missouristatebears.com",
        ["Monmouth"] = "monmouthhawks.com",
        ["Montana"] = "gogriz.com",
        ["Montana State"] = "msubobcats.com",
        ["Morehead State"] = "msueagles.com",
        ["Morgan State"] = "morganstatebears.com",
        ["Murray State"] = "goracers.com",
        ["New Hampshire"] = "unhwildcats.com",
        ["Nicholls"] = "geauxcolonels.com",
        ["Norfolk State"] = "nsuspartans.com",
        ["North Carolina A&T"] = "ncataggies.com",
        ["North Carolina Central"] = "nccueaglepride.com",
        ["North Dakota"] = "fightinghawks.com",
        ["North Dakota State"] = "gobison.com",
        ["Northern Arizona"] = "nauathletics.com",
        ["Northern Colorado"] = "unbears.com",
        ["Northern Iowa"] = "unipanthers.com",
        ["Northwestern State"] = "nsudemons.com",
        ["Penn"] = "pennathletics.com",
        ["Portland State"] = "goviks.com",
        ["Prairie View A&M"] = "pvamu.edu/pvamupanthers",
        ["Presbyterian"] = "gobluehose.com",
        ["Princeton"] = "goprincetontigers.com",
        ["Rhode Island"] = "gorhody.com",
        ["Richmond"] = "richmondspiders.com",
        ["Robert Morris"] = "rmucolonials.com",
        ["Sacramento State"] = "hornetsports.com",
        ["Sacred Heart"] = "sacredheartpioneers.com",
        ["Saint Francis"] = "sfuathletics.com",
        ["Samford"] = "samfordsports.com",
        ["San Diego"] = "usdtoreros.com",
        ["Southeast Missouri State"] = "gosoutheast.com",
        ["Southeastern Louisiana"] = "lionsports.net",
        ["Southern Illinois"] = "siusalukis.com",
        ["Southern Utah"] = "suutbirds.com",
        ["South Carolina State"] = "scsuathletics.com",
        ["South Dakota"] = "goyotes.com",
        ["South Dakota State"] = "gojacks.com",
        ["Stephen F. Austin"] = "sfajacks.com",
        ["Stetson"] = "gohatters.com",
        ["Stony Brook"] = "stonybrookathletics.com",
        ["Tarleton State"] = "tarletonsports.com",
        ["Tennessee State"] = "tsutigers.com",
        ["Tennessee Tech"] = "ttusports.com",
        ["Texas A&M-Commerce"] = "lionathletics.com",
        ["The Citadel"] = "citadelsports.com",
        ["Towson"] = "towsontigers.com",
        ["UC Davis"] = "ucdavisaggies.com",
        ["UIW"] = "uiwcardinals.com",
        ["UT Martin"] = "utmsports.com",
        ["Utah Tech"] = "utahtrailblazers.com",
        ["Valparaiso"] = "valpoathletics.com",
        ["Villanova"] = "villanova.com",
        ["VMI"] = "vmikeys.com",
        ["Wagner"] = "wagnerathletics.com",
        ["Weber State"] = "weberstatesports.com",
        ["Western Carolina"] = "catamountsports.com",
        ["Western Illinois"] = "goleathernecks.com",
        ["William & Mary"] = "tribeathletics.com",
        ["Wofford"] = "woffordterriers.com",
        ["Yale"] = "yalebulldogs.com",
        ["Youngstown State"] = "ysusports.com",
    };

    public static string[] TeamNames => Teams.Keys.ToArray();

    public static bool TryGetDomain(string teamName, out string domain)
        => Teams.TryGetValue(teamName, out domain);
}
