namespace Madden26Plugin.Roster;

public static class TeamMap
{
    public static Dictionary<string, string> TeamConference { get; } = new()
    {
        // ACC
        ["Boston College"] = "ACC",
        ["California"] = "ACC",
        ["Clemson"] = "ACC",
        ["Duke"] = "ACC",
        ["Florida State"] = "ACC",
        ["Georgia Tech"] = "ACC",
        ["Louisville"] = "ACC",
        ["Miami"] = "ACC",
        ["North Carolina"] = "ACC",
        ["NC State"] = "ACC",
        ["Pittsburgh"] = "ACC",
        ["SMU"] = "ACC",
        ["Stanford"] = "ACC",
        ["Syracuse"] = "ACC",
        ["Virginia"] = "ACC",
        ["Virginia Tech"] = "ACC",
        ["Wake Forest"] = "ACC",

        // Big Ten
        ["Illinois"] = "Big Ten",
        ["Indiana"] = "Big Ten",
        ["Iowa"] = "Big Ten",
        ["Maryland"] = "Big Ten",
        ["Michigan"] = "Big Ten",
        ["Michigan State"] = "Big Ten",
        ["Minnesota"] = "Big Ten",
        ["Nebraska"] = "Big Ten",
        ["Northwestern"] = "Big Ten",
        ["Ohio State"] = "Big Ten",
        ["Oregon"] = "Big Ten",
        ["Penn State"] = "Big Ten",
        ["Purdue"] = "Big Ten",
        ["Rutgers"] = "Big Ten",
        ["UCLA"] = "Big Ten",
        ["USC"] = "Big Ten",
        ["Washington"] = "Big Ten",
        ["Wisconsin"] = "Big Ten",

        // Big 12
        ["Arizona"] = "Big 12",
        ["Arizona State"] = "Big 12",
        ["Baylor"] = "Big 12",
        ["BYU"] = "Big 12",
        ["Cincinnati"] = "Big 12",
        ["Colorado"] = "Big 12",
        ["Houston"] = "Big 12",
        ["Iowa State"] = "Big 12",
        ["Kansas"] = "Big 12",
        ["Kansas State"] = "Big 12",
        ["Oklahoma State"] = "Big 12",
        ["TCU"] = "Big 12",
        ["Texas Tech"] = "Big 12",
        ["UCF"] = "Big 12",
        ["Utah"] = "Big 12",
        ["West Virginia"] = "Big 12",

        // SEC
        ["Alabama"] = "SEC",
        ["Arkansas"] = "SEC",
        ["Auburn"] = "SEC",
        ["Florida"] = "SEC",
        ["Georgia"] = "SEC",
        ["Kentucky"] = "SEC",
        ["LSU"] = "SEC",
        ["Mississippi State"] = "SEC",
        ["Missouri"] = "SEC",
        ["Oklahoma"] = "SEC",
        ["Ole Miss"] = "SEC",
        ["South Carolina"] = "SEC",
        ["Tennessee"] = "SEC",
        ["Texas"] = "SEC",
        ["Texas A&M"] = "SEC",
        ["Vanderbilt"] = "SEC",

        // AAC
        ["Army"] = "AAC",
        ["Charlotte"] = "AAC",
        ["East Carolina"] = "AAC",
        ["Florida Atlantic"] = "AAC",
        ["Memphis"] = "AAC",
        ["Navy"] = "AAC",
        ["North Texas"] = "AAC",
        ["Rice"] = "AAC",
        ["South Florida"] = "AAC",
        ["Temple"] = "AAC",
        ["Tulane"] = "AAC",
        ["Tulsa"] = "AAC",
        ["UAB"] = "AAC",
        ["UTSA"] = "AAC",

        // Conference USA
        ["FIU"] = "Conference USA",
        ["Jacksonville State"] = "Conference USA",
        ["Kennesaw State"] = "Conference USA",
        ["Liberty"] = "Conference USA",
        ["Louisiana Tech"] = "Conference USA",
        ["Middle Tennessee"] = "Conference USA",
        ["New Mexico State"] = "Conference USA",
        ["Sam Houston"] = "Conference USA",
        ["UTEP"] = "Conference USA",
        ["Western Kentucky"] = "Conference USA",

        // MAC
        ["Akron"] = "MAC",
        ["Ball State"] = "MAC",
        ["Bowling Green"] = "MAC",
        ["Buffalo"] = "MAC",
        ["Central Michigan"] = "MAC",
        ["Eastern Michigan"] = "MAC",
        ["Kent State"] = "MAC",
        ["Miami (OH)"] = "MAC",
        ["Northern Illinois"] = "MAC",
        ["Ohio"] = "MAC",
        ["Toledo"] = "MAC",
        ["Western Michigan"] = "MAC",

        // Mountain West
        ["Air Force"] = "Mountain West",
        ["Boise State"] = "Mountain West",
        ["Colorado State"] = "Mountain West",
        ["Fresno State"] = "Mountain West",
        ["Hawaii"] = "Mountain West",
        ["Nevada"] = "Mountain West",
        ["New Mexico"] = "Mountain West",
        ["San Diego State"] = "Mountain West",
        ["San José State"] = "Mountain West",
        ["UNLV"] = "Mountain West",
        ["Utah State"] = "Mountain West",
        ["Wyoming"] = "Mountain West",

        // Sun Belt
        ["Appalachian State"] = "Sun Belt",
        ["Arkansas State"] = "Sun Belt",
        ["Coastal Carolina"] = "Sun Belt",
        ["Georgia Southern"] = "Sun Belt",
        ["Georgia State"] = "Sun Belt",
        ["James Madison"] = "Sun Belt",
        ["Louisiana"] = "Sun Belt",
        ["Louisiana-Monroe"] = "Sun Belt",
        ["Marshall"] = "Sun Belt",
        ["Old Dominion"] = "Sun Belt",
        ["South Alabama"] = "Sun Belt",
        ["Southern Miss"] = "Sun Belt",
        ["Texas State"] = "Sun Belt",
        ["Troy"] = "Sun Belt",

        // Independents
        ["Connecticut"] = "Independents",
        ["Notre Dame"] = "Independents",
        ["UMass"] = "Independents",

        // FCS
        ["Alabama A&M"] = "FCS",
        ["Alabama State"] = "FCS",
        ["Alcorn State"] = "FCS",
        ["Arkansas-Pine Bluff"] = "FCS",
        ["Austin Peay"] = "FCS",
        ["Bethune-Cookman"] = "FCS",
        ["Brown"] = "FCS",
        ["Butler"] = "FCS",
        ["Campbell"] = "FCS",
        ["Central Arkansas"] = "FCS",
        ["Central Connecticut"] = "FCS",
        ["Charleston Southern"] = "FCS",
        ["Chattanooga"] = "FCS",
        ["Columbia"] = "FCS",
        ["Cornell"] = "FCS",
        ["Dartmouth"] = "FCS",
        ["Davidson"] = "FCS",
        ["Dayton"] = "FCS",
        ["Delaware State"] = "FCS",
        ["Drake"] = "FCS",
        ["Eastern Illinois"] = "FCS",
        ["Eastern Kentucky"] = "FCS",
        ["Eastern Washington"] = "FCS",
        ["Elon"] = "FCS",
        ["Florida A&M"] = "FCS",
        ["Fordham"] = "FCS",
        ["Furman"] = "FCS",
        ["Gardner-Webb"] = "FCS",
        ["Georgetown"] = "FCS",
        ["Grambling State"] = "FCS",
        ["Hampton"] = "FCS",
        ["Harvard"] = "FCS",
        ["Holy Cross"] = "FCS",
        ["Howard"] = "FCS",
        ["Idaho"] = "FCS",
        ["Idaho State"] = "FCS",
        ["Illinois State"] = "FCS",
        ["Indiana State"] = "FCS",
        ["Jackson State"] = "FCS",
        ["Lafayette"] = "FCS",
        ["Lehigh"] = "FCS",
        ["Lindenwood"] = "FCS",
        ["LIU"] = "FCS",
        ["Maine"] = "FCS",
        ["Marist"] = "FCS",
        ["McNeese"] = "FCS",
        ["Mercer"] = "FCS",
        ["Mississippi Valley State"] = "FCS",
        ["Missouri State"] = "FCS",
        ["Monmouth"] = "FCS",
        ["Montana"] = "FCS",
        ["Montana State"] = "FCS",
        ["Morehead State"] = "FCS",
        ["Morgan State"] = "FCS",
        ["Murray State"] = "FCS",
        ["New Hampshire"] = "FCS",
        ["Nicholls"] = "FCS",
        ["Norfolk State"] = "FCS",
        ["North Carolina A&T"] = "FCS",
        ["North Carolina Central"] = "FCS",
        ["North Dakota"] = "FCS",
        ["North Dakota State"] = "FCS",
        ["Northern Arizona"] = "FCS",
        ["Northern Colorado"] = "FCS",
        ["Northern Iowa"] = "FCS",
        ["Northwestern State"] = "FCS",
        ["Penn"] = "FCS",
        ["Portland State"] = "FCS",
        ["Prairie View A&M"] = "FCS",
        ["Presbyterian"] = "FCS",
        ["Princeton"] = "FCS",
        ["Rhode Island"] = "FCS",
        ["Richmond"] = "FCS",
        ["Robert Morris"] = "FCS",
        ["Sacramento State"] = "FCS",
        ["Sacred Heart"] = "FCS",
        ["Saint Francis"] = "FCS",
        ["Samford"] = "FCS",
        ["San Diego"] = "FCS",
        ["Southeast Missouri State"] = "FCS",
        ["Southeastern Louisiana"] = "FCS",
        ["Southern Illinois"] = "FCS",
        ["Southern Utah"] = "FCS",
        ["South Carolina State"] = "FCS",
        ["South Dakota"] = "FCS",
        ["South Dakota State"] = "FCS",
        ["Stephen F. Austin"] = "FCS",
        ["Stetson"] = "FCS",
        ["Stony Brook"] = "FCS",
        ["Tarleton State"] = "FCS",
        ["Tennessee State"] = "FCS",
        ["Tennessee Tech"] = "FCS",
        ["Texas A&M-Commerce"] = "FCS",
        ["The Citadel"] = "FCS",
        ["Towson"] = "FCS",
        ["UC Davis"] = "FCS",
        ["UIW"] = "FCS",
        ["UT Martin"] = "FCS",
        ["Utah Tech"] = "FCS",
        ["Valparaiso"] = "FCS",
        ["Villanova"] = "FCS",
        ["VMI"] = "FCS",
        ["Wagner"] = "FCS",
        ["Weber State"] = "FCS",
        ["Western Carolina"] = "FCS",
        ["Western Illinois"] = "FCS",
        ["William & Mary"] = "FCS",
        ["Wofford"] = "FCS",
        ["Yale"] = "FCS",
        ["Youngstown State"] = "FCS",
    };

    public static string GetConference(string teamName)
        => TeamConference.TryGetValue(teamName, out var conf) ? conf : "Unassigned";

    public static string[] AllTeamNames => TeamConference.Keys.ToArray();

    public static string[] AllConferences
        => TeamConference.Values.Distinct().OrderBy(c => c).ToArray();

    public static string[] GetTeams(string conference)
        => TeamConference.Where(kv => kv.Value == conference)
                         .Select(kv => kv.Key)
                         .OrderBy(t => t)
                         .ToArray();
}
